# for development environment
version: '3.9'

services:
  postgres:
    container_name: my_postgres_container
    image: postgres:alpine # Use the Alpine version
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - '5432:5432' # Expose PostgreSQL port

  redis:
    container_name: my_redis_container
    image: redis:latest
    ports:
      - '6379:6379' # Expose Redis port
